name: 'Pytest run'
description: 'Runs recent elasticsearch version'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  elasticsearch:
    description: 'Elasticsearch version'
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v6
    with:
      python-version: ${{ inputs.python-version }}
  - uses: actions/cache@v5
    with:
      path: ~/elasticsearch
      key: elasticsearch-${{ inputs.elasticsearch }}
  - name: Setup elasticsearch
    uses: ankane/setup-elasticsearch@v1
    with:
      elasticsearch-version: ${{ inputs.elasticsearch }}
  - name: Run test
    uses: fizyk/actions-reuse/.github/actions/pipenv@v4.1.1
    with:
      python-version: ${{ inputs.python-version }}
      command: pytest --elasticsearch-executable=$ES_HOME/bin/elasticsearch -p no:xdist --cov-report=xml
      allow-prereleases: true
  - name: Run xdist test
    uses: fizyk/actions-reuse/.github/actions/pipenv@v4.1.1
    with:
      python-version: ${{ inputs.python-version }}
      command: pytest --elasticsearch-executable=$ES_HOME/bin/elasticsearch -n auto --max-worker-restart=0 --cov-report=xml:coverage-xdist.xml
      allow-prereleases: true
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v5
    with:
      flags: linux,elastic-${{ inputs.elasticsearch }}
      env_vars: OS, PYTHON
      fail_ci_if_error: false
