name: 'Pytest run'
description: 'Runs tests against Elasticsearch 8'
inputs:
  python-version:  # id of input
    description: 'Python version to use'
    required: true
  elasticsearch:
    description: 'Elasticsearch version'
    required: true
runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v6
    with:
      python-version: ${{ inputs.python-version }}
  - uses: actions/cache@v5
    with:
      path: ~/elasticsearch
      key: elasticsearch-${{ inputs.elasticsearch }}
  - name: Setup elasticsearch
    uses: ankane/setup-elasticsearch@v1
    with:
      elasticsearch-version: ${{ inputs.elasticsearch }}
  - name: Prep environment
    shell: bash
    run: pip install pipenv && pipenv install --dev
  - name: Downgrade elasticsearch
    shell: bash
    run: pipenv run pip install -r oldest/requirements.txt
  - name: Run test
    shell: bash
    run: pipenv run pytest -c pyproject.oldest.toml --elasticsearch-executable=$ES_HOME/bin/elasticsearch -p no:xdist --cov-report=xml
  - name: Run xdist test
    shell: bash
    run: pipenv run pytest -c pyproject.oldest.toml --elasticsearch-executable=$ES_HOME/bin/elasticsearch -n auto --max-worker-restart=0 --cov-report=xml:coverage-xdist.xml
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v5
    with:
      flags: linux,elastic-${{ inputs.elasticsearch }}
      env_vars: OS, PYTHON
      fail_ci_if_error: false
